### PR TITLE
BUG/MINOR: sync cm name with config argument

### PR DESCRIPTION
**Pull request by dosmanak**
fixes 5eace95 namespace name change

### CODE REVIEW

**Comment by Mo3m3n** [comment]
Thanks @dosmanak 
In the same context,  path of default-backend-service needs to be fixed too:
https://github.com/haproxytech/kubernetes-ingress/blob/1966e37d7315be071fe15c4321fce2f9aaf5578e/deploy/haproxy-ingress-daemonset.yaml#L168
https://github.com/haproxytech/kubernetes-ingress/blob/1966e37d7315be071fe15c4321fce2f9aaf5578e/deploy/haproxy-ingress.yaml#L169

And this one 
https://github.com/haproxytech/kubernetes-ingress/blob/1966e37d7315be071fe15c4321fce2f9aaf5578e/deploy/tests/rebuild.sh#L22

**Comment by dosmanak** [comment]
Yeah, you're right. I have in my kustomize file and forgot to put it here. Thank you for pointing that out. I've added second commit.

**Comment by Mo3m3n** [comment]
Only this one left (replace default -> haproxy-controller) as already mentioned  and this is good to be merged 
https://github.com/haproxytech/kubernetes-ingress/blob/1966e37d7315be071fe15c4321fce2f9aaf5578e/deploy/tests/rebuild.sh#L22

**Comment by Mo3m3n** [comment]
Thanks @dosmanak

**Pull request merged**
