### PR TITLE
BUG/MINOR: Minor spelling mistake fix.

### PR DESCRIPTION
**Pull request by LarsBingBong**
Spotted when going through trace level logs on a Kubernetes cluster using this project.

### CODE REVIEW

**Comment by ivanmatmati** [comment]
Hi @LarsBingBong , could you change the commit message and prefix it with BUG/MINOR like in 
```
BUG/MINOR: Don't initialize Backend.DefaultServer when not used
```

**Comment by ivanmatmati** [comment]
Hi @LarsBingBong , could you change the commit message and prefix it with BUG/MINOR like in 
```
BUG/MINOR: Don't initialize Backend.DefaultServer when not used
```

**Comment by LarsBingBong** [comment]
Is the change I've done enough?

**Comment by ivanmatmati** [comment]
No, the commit message must be changed not the title of PR.

**Comment by LarsBingBong** [comment]
Should be good now @ivanmatmati and sorry my bad. Hadn't tried `rewording` a commit msg before.

**Comment by ivanmatmati** [comment]
We're almost there. You need to add the colon after BUG/MINOR like in the example because it fails the commit message check.

**Comment by LarsBingBong** [comment]
Now we're there 🤞🏿

**Comment by ivanmatmati** [comment]
Thanks.

**Comment by ivanmatmati** [comment]
Thanks.

**Pull request merged**
