### PR TITLE
Typo on HAProxy Community Slack link

### PR DESCRIPTION
**Pull request by prometherion**

### CODE REVIEW

**Comment by oktalz** [comment]
hi @prometherion

**Comment by oktalz** [comment]
thx fort this,

can you just change commit message to follow our guidelines?
in short, it should be

```
DOC/MINOR: readme: Typo on HAProxy Community Slack link
```

**Comment by prometherion** [comment]
my bad, I wasn't aware of the commit message convention

**Comment by oktalz** [comment]
no problem, 
also ignore this build fails notifications :)
Github has problems last few days.

**Comment by Mo3m3n** [comment]
There was a Typo in the commit message "C/MINOR" instead of "DOC/MINOR"
I have fixed it and merged the commit.

**Pull request closed without merging**
